player_manager.AddValidModel( "VaasPirateAssaulter1", "models/player/fc3pirate_1.mdl" )
player_manager.AddValidModel( "VaasPirateAssaulter2", "models/player/fc3pirate_2.mdl" )
player_manager.AddValidModel( "VaasPirateAssaulter3", "models/player/fc3pirate_3.mdl" )
player_manager.AddValidModel( "VaasPirateAssaulter4", "models/player/fc3pirate_4.mdl" )
player_manager.AddValidModel( "VaasPirateAssaulter5", "models/player/fc3pirate_5.mdl" )
player_manager.AddValidModel( "VaasPirateAssaulter6", "models/player/fc3pirate_6.mdl" )
player_manager.AddValidModel( "VaasPirateAssaulter7", "models/player/fc3pirate_7.mdl" )
player_manager.AddValidModel( "VaasPirateAssaulter8", "models/player/fc3pirate_8.mdl" )
player_manager.AddValidModel( "VaasPirateAssaulter9", "models/player/fc3pirate_9.mdl" )
player_manager.AddValidModel( "VaasPirateAssaulter10", "models/player/fc3pirate_10.mdl" )
player_manager.AddValidHands( "VaasPirateAssaulter1", "models/weapons/c_arms_jason.mdl", 0, "00000000" )
player_manager.AddValidHands( "VaasPirateAssaulter2", "models/weapons/c_arms_jason.mdl", 0, "00000000" )
player_manager.AddValidHands( "VaasPirateAssaulter3", "models/weapons/c_arms_jason.mdl", 0, "00000000" )
player_manager.AddValidHands( "VaasPirateAssaulter4", "models/weapons/c_arms_jason.mdl", 0, "00000000" )
player_manager.AddValidHands( "VaasPirateAssaulter5", "models/weapons/c_arms_jason.mdl", 0, "00000000" )
player_manager.AddValidHands( "VaasPirateAssaulter6", "models/weapons/c_arms_jason.mdl", 0, "00000000" )
player_manager.AddValidHands( "VaasPirateAssaulter7", "models/weapons/c_arms_jason.mdl", 0, "00000000" )
player_manager.AddValidHands( "VaasPirateAssaulter8", "models/weapons/c_arms_jason.mdl", 0, "00000000" )
player_manager.AddValidHands( "VaasPirateAssaulter9", "models/weapons/c_arms_jason.mdl", 0, "00000000" )
player_manager.AddValidHands( "VaasPirateAssaulter10", "models/weapons/c_arms_jason.mdl", 0, "00000000" )

player_manager.AddValidModel( "HoytPrivateerDefender", "models/player/privateer_1.mdl" )
player_manager.AddValidHands( "HoytPrivateerDefender", "models/weapons/c_arms_privateer.mdl", 0, "00000000" )
