player_manager.AddValidModel( "Vaas Pirate Assaulter 1", "models/player/fc3pirate_1.mdl" )
player_manager.AddValidModel( "Vaas Pirate Assaulter 2", "models/player/fc3pirate_2.mdl" )
player_manager.AddValidModel( "Vaas Pirate Assaulter 3", "models/player/fc3pirate_3.mdl" )
player_manager.AddValidModel( "Vaas Pirate Assaulter 4", "models/player/fc3pirate_4.mdl" )
player_manager.AddValidModel( "Vaas Pirate Assaulter 5", "models/player/fc3pirate_5.mdl" )
player_manager.AddValidModel( "Vaas Pirate Assaulter 6", "models/player/fc3pirate_6.mdl" )
player_manager.AddValidModel( "Vaas Pirate Assaulter 7", "models/player/fc3pirate_7.mdl" )
player_manager.AddValidModel( "Vaas Pirate Assaulter 8", "models/player/fc3pirate_8.mdl" )
player_manager.AddValidModel( "Vaas Pirate Assaulter 9", "models/player/fc3pirate_9.mdl" )
player_manager.AddValidModel( "Vaas Pirate Assaulter 10", "models/player/fc3pirate_10.mdl" )
player_manager.AddValidHands( "Vaas Pirate Assaulter 1", "models/weapons/c_arms_jason.mdl", 0, "00000000" )
player_manager.AddValidHands( "Vaas Pirate Assaulter 2", "models/weapons/c_arms_jason.mdl", 0, "00000000" )
player_manager.AddValidHands( "Vaas Pirate Assaulter 3", "models/weapons/c_arms_jason.mdl", 0, "00000000" )
player_manager.AddValidHands( "Vaas Pirate Assaulter 4", "models/weapons/c_arms_jason.mdl", 0, "00000000" )
player_manager.AddValidHands( "Vaas Pirate Assaulter 5", "models/weapons/c_arms_jason.mdl", 0, "00000000" )
player_manager.AddValidHands( "Vaas Pirate Assaulter 6", "models/weapons/c_arms_jason.mdl", 0, "00000000" )
player_manager.AddValidHands( "Vaas Pirate Assaulter 7", "models/weapons/c_arms_jason.mdl", 0, "00000000" )
player_manager.AddValidHands( "Vaas Pirate Assaulter 8", "models/weapons/c_arms_jason.mdl", 0, "00000000" )
player_manager.AddValidHands( "Vaas Pirate Assaulter 9", "models/weapons/c_arms_jason.mdl", 0, "00000000" )
player_manager.AddValidHands( "Vaas Pirate Assaulter 10", "models/weapons/c_arms_jason.mdl", 0, "00000000" )

player_manager.AddValidModel( "Privateer", "models/player/privateer_1.mdl" )
list.Set( "PlayerOptionsModel", "Privateer", "models/player/privateer_1.mdl" )
player_manager.AddValidHands( "Privateer", "models/weapons/c_arms_privateer.mdl", 0, "00000000" )
