Achievements=Достижения

ReinforcementsBar=ПОДКРЕПЛЕНИЯ

AchievementsMenuPagePrev=Пред
AchievementsMenuPageNext=След

CascadeShadowMapping=Cascade Shadow Mapping
CascadeShadowMappingInformation=KM_CM's Addon Cascade Shadow Mapping works on the base of Xenthio's. His addon is awesome, and I would be a bad person if I didn't leave the link to his Patreon as in his own addon:\nhttps://www.patreon.com/xenthio\nHis version of CSM is here:\nhttps://github.com/Xenthio/RealCSM
ShadowDepthResolution=Shadow Depth Resolution
ShadowDepthResolutionHelp=Recommended for weak devices is the minimum bound
CascadeShadowMappingHelp=Turn on for dynamic shadows, turn off for RTT shadows

Actor=Actor
actor=Actor

tool.actorcover.name=Cover
tool.ActorCover.name=Cover
tool.actorcover.desc=Requires `developer 1`. Allows setting covers used by BaseActor.
tool.actorcover.0=Left click to create, right click to delete.

tool.actorcoverlinker.name=Cover Linker
tool.ActorCoverLinker.name=Cover Linker
tool.actorcoverlinker.desc=Requires `developer 1`. Allows linking covers used by BaseActor.
tool.actorcoverlinker.0=Left click to link, right click to delete a link.

tool.navigationmeshconnector.name=Connector
tool.NavigationMeshConnector.name=Connector
tool.navigationmeshconnector.desc=Requires `nav_edit 1`. Superadmin only. Automatically saves. Connects navigation mesh areas.
tool.navigationmeshconnector.0=Left click to select an area and then to connect or disconnect it. Reload to forget the selected area.

NavigationMeshConnectorToolHelp=Requires `nav_edit 1`. Superadmin only. Automatically saves. Select an area and then connect or disconnect it to another. Initially made to fix the lack of proper jumping connections on maps. This tool will make connections going both ways, because some Actors or NextBots may be able to jump infinitely high. In fact, you should probably never use one way connections.

ActorCoverToolHelp=Requires `developer 1`. Select point A, point B, and then the side to create a static cover.

CombineCivilProtection=Юнит Гражданской Обороны Альянса
combinecivilprotection=Юнит Гражданской Обороны Альянса

CombineElite=Элитный Солдат Альянса
combineelite=Элитный Солдат Альянса

CombineSoldier=Солдат Альянса
combinesoldier=Солдат Альянса

CombineTurret=Турель Альянса
combineturret=Турель Альянса

env_explosion=Взрыв

env_projectedtexture=Свет

Flare=Сигнальная Ракета
flare=Сигнальная Ракета

weapon_striderbuster=Девайс Магнуссона
MagnussonDevice=Девайс Магнуссона
magnussondevice=Девайс Магнуссона

grenade_helicopter=Бомба Вертолёта Альянса
CombineHelicopterBomb=Бомба Вертолёта Альянса
combinehelicopterbomb=Бомба Вертолёта Альянса

HumanSWAT=SWAT Operative
humanswat=SWAT Operative

HumanTerrorist=Террорист
humanterrorist=Террорист

NavigationTesterHuman=Тестер Навигационной Сетки Людей
navigationtesterhuman=Тестер Навигационной Сетки Людей

MudSkipper=Mudskipper
mudskipper=Mudskipper

SimpleSiren=Сирена
simplesiren=Сирена

AK47=AK-47
ak47=AK-47
AWM=AI AWM
awm=AI AWM
BenelliM4Super90=Benelli M4 Super 90
benellim4super90=Benelli M4 Super 90
DesertEagle=Desert Eagle
deserteagle=Desert Eagle
FAMAS=FAMAS
famas=FAMAS
FlashBang=Flashbang
flashbang=Flashbang
Glock18=Glock-18
glock18=Glock-18
Hands=Hands
hands=Hands
M16A4=M16A4
m16a4=M16A4
M249SAW=M249SAW
m249saw=M249SAW
MAC10=MAC-10
mac10=MAC-10
MP5=H&K MP5
mp5=H&K MP5
UMP45=H&K UMP45
ump45=H&K UMP45
USP=USP
usp=USP
weapon_357=Colt Python
weapon_ar2=OSIPR
OSIEW=OSIEW
osiew=OSIEW
weapon_flaregun=Flare Gun
weapon_frag=Combine Extractor
weapon_medkit=Combine Medical Kit
item_healthkit=Combine Medical Kit
weapon_pistol=USP Match
weapon_shotgun=SPAS-12
weapon_smg1=H&K MP7

VideoCamera=Видео Камера
videocamera=Видео Камера

VideoCameraInstructions=Primary to start or stop recording. Videos are stored in the videos folder in WEBM format.
VideoCameraDescription=Video camera. Unknown manufacturer.

Tip_Walking1=Always remember that it is quieter to crouch than to walk, and to walk than to sprint.
Tip_Walking2=It is easy to fall off ledges. When you're sprinting, it is hard to see your direction of motion due to all the bobbing, which might lead you to falling.
Tip_Walking3=Just like swimming, even crouching makes some noise, even if very little.
Tip_Walking4=Falling is very lethal. Even falling off a simple roof can kill you.
Tip_Walking5=If something is chasing you, only try to break line of sight after you've gotten away far enough, or you might be caught again. This is also why fast things are dangerous.
Tip_Walking6=Walking in water causes loud splashes. If it's deep enough, it is recommended to swim instead. If it isn't, avoid it.
Tip_Walking7=Walking on the ocean floor doesn't cause splashing, as opposed to walking in shallow waters.
Tip_Walking8=Different surfaces make different amounts of noise. The loudest is water, the exception being the ocean floor, walking on which makes almost no sound.

Tip_Swimming1=It is hard to spot you underwater, but easy to spot you on the surface of it. Swimming is also relatively quiet.
Tip_Swimming2=Be very quick if you need to get into an underwater maze you don't know the layout of. Oxygen is not infinite.
Tip_Swimming3=Be careful when resurfacing, as you are much visible on the surface of the water than below it. If you're certain you will not die from asphyxiation, it might be worth waiting for that airboat to pass.
Tip_Swimming4=Always remember that you may not be the only thing swimming there. Swimming in clearer waters fixes this problem, but makes you easier to spot.
Tip_Swimming5=Sometimes, the best way to outrun a water based predator is to simply head to nearest land.
Tip_Swimming6=It is preferable to swim inside deep enough water, as opposed to walking on it, as that causes loud splashing.
Tip_Swimming7=Walking on the ocean floor makes no splashing, as opposed to walking in shallow waters.
Tip_Swimming8=While it is impossible to take legitimate, peekable cover in water, it is still possible to move behind objects to break line of sight. The ability to move in all three axes grants even more freedom to do so than on the ground.

Caption_vo/npc/male01/takecover02.wav=Take cover!
Caption_vo/npc/male01/gethellout.wav=GET!! THE HELL!! OUTTA HERE!!!
Caption_vo/npc/male01/runforyourlife01.wav=RUN FOR YOUR LIFE!!!
Caption_vo/npc/male01/runforyourlife02.wav=RUN FOR YOUR LIFE!!!
Caption_vo/npc/male01/runforyourlife03.wav=RUN FOR YOUR LIFE!!!

Caption_vo/npc/male01/squad_away02.wav=Over here!
Caption_vo/npc/male01/squad_away03.wav=Follow me!

Caption_vo/npc/male01/leadtheway01.wav=You lead the way!
Caption_vo/npc/male01/leadtheway02.wav=Lead the way!
Caption_vo/npc/male01/readywhenyouare01.wav=Ready when you are!
Caption_vo/npc/male01/readywhenyouare02.wav=Ready when <I>you<I> are!
Caption_vo/npc/male01/okimready.wav=Okay, I'm ready!

Caption_vo/npc/male01/letsgo01.wav=Let's <I>GO!<I>
Caption_vo/npc/male01/letsgo02.wav=Let's go!
Caption_vo/npc/male01/squad_follow02.wav=C'mon, everybody!
Caption_vo/npc/male01/squad_follow03.wav=Let's get moving!
Caption_vo/npc/male01/squad_approach02.wav=Here we come!
Caption_vo/npc/male01/squad_approach03.wav=On our way!

Caption_npc/combine_soldier/vo/contact.wav=Contact!
Caption_npc/combine_soldier/vo/contactconfim.wav=Contact confirm!
Caption_npc/combine_soldier/vo/contactconfirmprosecuting.wav=Contact confirm, prosecuting!
Caption_npc/combine_soldier/vo/fullactive.wav=Full active!
Caption_npc/combine_soldier/vo/closing.wav=Closing!
Caption_npc/combine_soldier/vo/closing2.wav=Closing!
Caption_npc/combine_soldier/vo/unitisclosing.wav=Unit is closing!
Caption_npc/combine_soldier/vo/unitismovingin.wav=Unit is moving in!
Caption_npc/combine_soldier/vo/bearing.wav=Bearing!

Caption_npc/combine_soldier/vo/bodypackholding.wav=Body pack holding!
Caption_npc/combine_soldier/vo/cover.wav=Cover!
Caption_npc/combine_soldier/vo/coverhurt.wav=COVER!!!
Caption_npc/combine_soldier/vo/stabilizationteamholding.wav=Stabilization team holding in position!
Caption_npc/combine_soldier/vo/sharpzone.wav=Sharp zone!
Caption_npc/combine_soldier/vo/heavyresistance.wav=BE ADVISED, WE HAVE HEAVY RESISTANCE!!

Caption_npc/combine_soldier/vo/displace.wav=Displace!!
Caption_npc/combine_soldier/vo/displace2.wav=Displace!!

Caption_npc/combine_soldier/vo/hasnegativemovement.wav=Has negative movement.

Caption_npc/turret_floor/active.wav=[Whoosh!]
