p416=P416
P416=P416

taurusmodel44=Taurus Model 44
TaurusModel44=Taurus Model 44

krissvector=KRISS Vector
KRISSVector=KRISS Vector

coltm1911=Colt M1911
ColtM1911=Colt M1911

mkg=MKG
MKG=MKG

akm=AKM
AKM=AKM

zastavam93blackarrowshortrangescope=Zastava M93 Black Arrow Short Range Scope
ZastavaM93BlackArrowShortRangeScope=Zastava M93 Black Arrow Short Range Scope

zastavam93blackarrow=Zastava M93 Black Arrow
ZastavaM93BlackArrow=Zastava M93 Black Arrow

rookislandsbow=Rook Islands Bow
RookIslandsBow=Rook Islands Bow

humanvaaspirateassaulter=Vaas Pirate Assaulter
HumanVaasPirateAssaulter=Vaas Pirate Assaulter

Caption_VaasPirate/Assaulter/ICantBelieveILostHim_Motherfucker.wav=I can't believe I lost him!... Mother fucker!

Caption_VaasPirate/Assaulter/IFoundHim.wav=I FOUND HIM!!
Caption_VaasPirate/Assaulter/IFoundYou.wav=I FOUND YOU!
Caption_VaasPirate/Assaulter/Gotchu.wav=GOTCHU!
Caption_VaasPirate/Assaulter/GotchuFucker.wav=GOTCHU FUCKER!
Caption_VaasPirate/Assaulter/HahaIGotchu.wav=HAHA, I GOTCHU!
Caption_VaasPirate/Assaulter/ISeeHimHesThere.wav=I SEE HIM! HE'S THERE!
Caption_VaasPirate/Assaulter/ISeeHimHesThere2.wav=I SEE HIM! HE'S THERE!
Caption_VaasPirate/Assaulter/HesRightHere.wav=HE'S RIGHT HERE!

Caption_VaasPirate/Assaulter/RunFire.wav=RUN!!! FIRE!!

Caption_VaasPirate/Assaulter/ShitShit.wav=SHIT! SHIT!!
Caption_VaasPirate/Assaulter/ShitShit2.wav=SHIT! SHIT!!
Caption_VaasPirate/Assaulter/ShitShit3.wav=SHIT! SHIT!!
Caption_VaasPirate/Assaulter/FuckFuckFuckFuckFuckFuuck.wav=FUCK FUCK FUCK FUCK FUCK FUCK FUUCK!
Caption_VaasPirate/Assaulter/Shiiiit.wav=SHIIIIT!!
Caption_VaasPirate/Assaulter/Shiiit.wav=SHIIIT!!
Caption_VaasPirate/Assaulter/NoNoNo.wav=NONONO!
Caption_VaasPirate/Assaulter/Shit.wav=SHIT!
Caption_VaasPirate/Assaulter/Shit2.wav=SHIT!

Caption_VaasPirate/Assaulter/DaaamnMothafucka.wav=DAAAMN MOTHAFUCKA!
Caption_VaasPirate/Assaulter/OhMyGod.wav=OH MY GOD!
Caption_VaasPirate/Assaulter/HolyShit.wav=HOLY SHIT!
Caption_VaasPirate/Assaulter/Aah.wav=AAH!
Caption_VaasPirate/Assaulter/Aah2.wav=AAH!
Caption_VaasPirate/Assaulter/Oh.wav=OH!
Caption_VaasPirate/Assaulter/HolyFuckingShit.wav=HOLY FUCKING SHIT!
Caption_VaasPirate/Assaulter/UhAhAhAh.wav=UH AH AH AH!
Caption_VaasPirate/Assaulter/Hoh.wav=HOH!
Caption_VaasPirate/Assaulter/Fuck.wav=FUCK!
Caption_VaasPirate/Assaulter/Aha.wav=AHA!
Caption_VaasPirate/Assaulter/SonOfABitch.wav=SON OF A BITCH!

Caption_VaasPirate/Assaulter/YoureDead.wav=YOU'RE DEAD!
Caption_VaasPirate/Assaulter/YoureDead2.wav=YOU'RE DEAD!
Caption_VaasPirate/Assaulter/YoureDead3.wav=YOU'RE DEAD!
Caption_VaasPirate/Assaulter/YoureDeadNow.wav=YOU'RE DEAD NOW!
Caption_VaasPirate/Assaulter/YoureMine.wav=YOU'RE MINE!
Caption_VaasPirate/Assaulter/YoureMineNow.wav=YOU'RE MINE NOW!
Caption_VaasPirate/Assaulter/ImGonnaEatchuAlive.wav=I'M GONNA EATCHU ALIVE!
Caption_VaasPirate/Assaulter/ImGonnaEatchuAlive2.wav=I'M GONNA EATCHU ALIVE!
Caption_VaasPirate/Assaulter/ImGonnaEatchuAlive3.wav=I'M GONNA EATCHU ALIVE!
Caption_VaasPirate/Assaulter/ImGonnaEatchuAlive4.wav=I'M GONNA EATCHU ALIVE!
Caption_VaasPirate/Assaulter/ImNotScaredOfYou_Asshole.wav=I'M NOT SCARED OF YOU! ASSHOLE!
Caption_VaasPirate/Assaulter/ImNotScaredOfYouAsshole1.wav=I'M NOT SCARED OF YOU, ASSHOLE!
Caption_VaasPirate/Assaulter/ImNotScaredOfYouAsshole2.wav=I'M NOT SCARED OF YOU, ASSHOLE!
Caption_VaasPirate/Assaulter/ImNotScaredOfYouAsshole3.wav=I'M NOT SCARED OF YOU, ASSHOLE!
Caption_VaasPirate/Assaulter/SuckOnSomeBullets_Bitch.wav=SUCK ON SOME BULLETS, BITCH!
Caption_VaasPirate/Assaulter/SuckOnSomeBullets_Bitch2.wav=SUCK ON SOME BULLETS! BITCH!
Caption_VaasPirate/Assaulter/SuckOnSomeBulletsBitch.wav=SUCK ON SOME BULLETS BITCH!
Caption_VaasPirate/Assaulter/IAintEvenStartedYet.wav=I AIN'T EVEN STARTED YET!
Caption_VaasPirate/Assaulter/IAintEvenStartedYet2.wav=I AIN'T EVEN STARTED YET!!
Caption_VaasPirate/Assaulter/IAintEvenStartedYet3.wav=I AIN'T EVEN STARTED YET!
Caption_VaasPirate/Assaulter/WatchMeTakeHimDown.wav=WATCH ME TAKE HIM DOWN!

Caption_VaasPirate/Assaulter/ManYouSuck.wav=HAHAHAH, MAN, YOU SUCK!
Caption_VaasPirate/Assaulter/StopMeMotherfuckerStopMe.wav=STOP ME, MOTHERFUCKER! STOP ME!
Caption_VaasPirate/Assaulter/StopMeMotherfuckerStopMe2.wav=STOP ME, MOTHERFUCKER! STOP ME!

Caption_VaasPirate/Assaulter/ImComingForYou.wav=I'M COMING FOR YOU!
Caption_VaasPirate/Assaulter/ImComingForYou2.wav=I'M COMING FOR YOU!!
Caption_VaasPirate/Assaulter/ImMoving.wav=I'M MOVING!
Caption_VaasPirate/Assaulter/ImMoving2.wav=I'M MOVING!
Caption_VaasPirate/Assaulter/ImMoving3.wav=I'M MOVING!

Caption_VaasPirate/Assaulter/Chaarge.wav=CHAARGE!
Caption_VaasPirate/Assaulter/Chyaaarge.wav=CHYAAAARGE!
Caption_VaasPirate/Assaulter/ChaaargeHaaahahaha.wav=CHAAARGE, HAAAHAHAHA!
Caption_VaasPirate/Assaulter/ChaaargeOoohohohohoho.wav=CHAAARGE, OOOHOHOHOHOHO!
Caption_VaasPirate/Assaulter/ComeOnLetsGetHim.wav=COME ON! LET'S GET HIM!
Caption_VaasPirate/Assaulter/ComeOnLetsGetHim2.wav=COME ON! LET'S GET HIM!
Caption_VaasPirate/Assaulter/GetHimComeOn.wav=GET HIM! COME ON!

Caption_VaasPirate/Assaulter/ImPinnedDown.wav=I'M PINNED DOWN!
Caption_VaasPirate/Assaulter/ImPinnedDown2.wav=I'M PINNED DOWN!
Caption_VaasPirate/Assaulter/ImPinnedDown3.wav=I'M! PINNED! DOWN!
Caption_VaasPirate/Assaulter/ImPinnedDown4.wav=I'M PINNED DOWN!
Caption_VaasPirate/Assaulter/HelpImGettingHolesHere.wav=HELP, I'M GETTING HOLES HERE!
Caption_VaasPirate/Assaulter/HelpImGettingHolesHere2.wav=HELP, I'M GETTING HOLES HERE!

humanhoytprivateerdefender=Hoyt Privateer Defender
HumanHoytPrivateerDefender=Hoyt Privateer Defender

Caption_HoytPrivateer/Defender/ThoughYouCouldHide.wav=THOUGHT YOU COULD HIDE?!
Caption_HoytPrivateer/Defender/TargetSpotted.wav=TARGET SPOTTED!
Caption_HoytPrivateer/Defender/TargetSpotted2.wav=TARGET SPOTTED!
Caption_HoytPrivateer/Defender/ISeeYouThereMotherfucker.wav=I SEE YOU THERE MOTHERFUCKER!
Caption_HoytPrivateer/Defender/HeyTargets.wav=HEY! TARGETS!
Caption_HoytPrivateer/Defender/TargetOverThere.wav=TARGET, OVER THERE!
Caption_HoytPrivateer/Defender/TargetSighted.wav=TARGET SIGHTED!

Caption_HoytPrivateer/Defender/ImGonnaMakeYouBleed.wav=I'M GONNA MAKE YOU BLEED!
Caption_HoytPrivateer/Defender/YouGotNoChanceManNoChance.wav=YOU GOT NO CHANCE, MAN, NO CHANCE!
Caption_HoytPrivateer/Defender/YoureDead.wav=YOU'RE DEAD!

Caption_HoytPrivateer/Defender/EyAveYouBeenDoingThisLong.wav='EY! 'AVE YOU BEEN DOING THIS LONG?!
Caption_HoytPrivateer/Defender/StopWastingBulletsAndHitMe.wav=STOP WASTING BULLETS AND HIT ME!
Caption_HoytPrivateer/Defender/EyWouldItHelpIfIStoodStill.wav='EY! WOULD IT HELP IF I STOOD STILL?!
Caption_HoytPrivateer/Defender/KhahDamnYouSuck.wav=KHAH DAMN, YOU SUCK!
Caption_HoytPrivateer/Defender/MaybeIShootMyselfSoYouDontFeelSoBad.wav=MAYBE I SHOOT MYSELF, SO YOU DON'T FEEL SO BAD?!

Caption_HoytPrivateer/Defender/AdvancingCoverMe.wav=ADVANCING, COVER ME!
Caption_HoytPrivateer/Defender/Advancing.wav=ADVANCING!
Caption_HoytPrivateer/Defender/ImComingForYou.wav=I'M COMING FOR YOU!
Caption_HoytPrivateer/Defender/MovingIntoPositionGiveMeOverwatch.wav=MOVING INTO POSITION! GIVE ME OVERWATCH!

Caption_HoytPrivateer/Defender/HolyCrap.wav=HOLY CRAP!
Caption_HoytPrivateer/Defender/WhatTheHell.wav=WHAT. THE. HELL?!
Caption_HoytPrivateer/Defender/Woah.wav=WOAH!

Caption_HoytPrivateer/Defender/HelpImPinned.wav=HELP! I'M PINNED!
Caption_HoytPrivateer/Defender/ImPinnedDown.wav=I'M PINNED DOWN!

humanhoytprivateerheavy=Hoyt Privateer Heavy
HumanHoytPrivateerHeavy=Hoyt Privateer Heavy
